# Generated by Django 3.2.9 on 2021-11-18 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adhar_no', models.CharField(max_length=26)),
                ('mother_tounge', models.CharField(max_length=26)),
                ('email', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=10)),
                ('relegion', models.CharField(max_length=26)),
                ('caste', models.CharField(max_length=26)),
                ('status', models.BooleanField(default=False)),
                ('marital_status', models.CharField(max_length=26)),
                ('qualification', models.CharField(max_length=26)),
                ('profile_pic', models.FileField(default=False, upload_to='')),
                ('country', models.CharField(max_length=26)),
                ('state', models.CharField(max_length=26)),
                ('district', models.CharField(max_length=26)),
                ('blood_group', models.CharField(max_length=26)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=255)),
                ('sbdate', models.DateField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.courses')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Subjectstaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.courses')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffs')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStaffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReportStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.CharField(max_length=255)),
                ('leave_message', models.TextField()),
                ('leave_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_name', models.CharField(max_length=25)),
                ('assign_text', models.CharField(max_length=255)),
                ('assign_upload', models.FileField(upload_to='')),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('times', models.TimeField(auto_now_add=True)),
                ('State', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.courses')),
                ('staff_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.subjects')),
            ],
        ),
    ]
