# Generated by Django 3.2.9 on 2021-11-18 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Students_bulk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csv_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentname', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('admissionno', models.CharField(max_length=255)),
                ('bdate', models.DateField(max_length=8)),
                ('gender', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('adhar_no', models.CharField(max_length=26)),
                ('mobileno', models.CharField(max_length=10)),
                ('parents_mobileno1', models.CharField(max_length=10)),
                ('parents_mobileno2', models.CharField(max_length=10)),
                ('parents_email', models.CharField(max_length=255)),
                ('mothername', models.CharField(max_length=100)),
                ('motheroccupation', models.CharField(max_length=100)),
                ('motherincome', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=255)),
                ('fatheroccupation', models.CharField(max_length=255)),
                ('fatherincome', models.CharField(max_length=255)),
                ('relegion', models.CharField(max_length=26)),
                ('caste', models.CharField(max_length=26)),
                ('staffchild_status', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=26)),
                ('state', models.CharField(max_length=26)),
                ('district', models.CharField(max_length=26)),
                ('blood_group', models.CharField(max_length=26)),
                ('language_group', models.CharField(max_length=26)),
                ('mother_tounge', models.CharField(max_length=26)),
                ('email', models.CharField(max_length=255)),
                ('profile_pic', models.FileField(upload_to='')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.courses')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.sessionyearmodel')),
            ],
        ),
        migrations.CreateModel(
            name='studentnotice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Notice', models.TextField()),
                ('notice_upload', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.students')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=255)),
                ('total_mark', models.CharField(max_length=255)),
                ('mark_percentage', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.courses')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.students')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReportStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.CharField(max_length=255)),
                ('leave_message', models.TextField()),
                ('leave_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.students')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.attendance')),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.courses')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student.students')),
                ('subject_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student.students'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.subjects'),
        ),
    ]
